INSERT INTO public.daily_missions (domain, level, title, description, mission_type, content, jarvis_intro, jarvis_bravo, xp, is_active) VALUES

-- ═══════════════ IA_PRO — BEGINNER ═══════════════
('ia_pro', 'beginner', 'Premier prompt', 'Écrivez votre tout premier prompt IA et observez le résultat.', 'action', '{"task": "Ouvrez KITT IA et tapez : \"Explique-moi ce qu''est ChatGPT comme si j''avais 12 ans.\" Lisez la réponse et notez ce qui vous surprend.", "hint": "Un bon prompt est clair, précis et donne un contexte."}', 'Votre aventure IA commence maintenant. Un seul prompt peut tout changer.', 'Premier prompt envoyé — vous venez de franchir le cap que 80% des gens ne franchissent jamais. Bravo !', 10, true),

('ia_pro', 'beginner', 'Résumer un article', 'Utilisez l''IA pour résumer un article en 5 points clés.', 'action', '{"task": "Copiez un article de presse (ou utilisez celui-ci : \"Les 7 usages professionnels de l''IA en 2025\") et demandez à KITT IA : \"Résume cet article en 5 points clés, en 3 lignes max chacun.\"", "hint": "Collez le texte directement dans le chat pour de meilleurs résultats."}', 'Fini de lire des articles en entier. L''IA va faire le boulot pour vous.', 'Vous venez de gagner 20 minutes. Multipliez ça par chaque article que vous lisez — c''est votre nouveau superpouvoir.', 10, true),

('ia_pro', 'beginner', 'Générer un email pro', 'Créez un email professionnel en moins de 60 secondes avec l''IA.', 'action', '{"task": "Demandez à KITT IA : \"Rédige un email professionnel pour demander un rendez-vous à un prospect. Ton : direct et chaleureux. Longueur : 80 mots max.\" Adaptez le résultat à votre contexte.", "hint": "Précisez toujours le ton et la longueur désirés."}', 'La rédaction d''emails vous prend du temps ? Plus maintenant.', 'Email généré en 10 secondes. Votre inbox ne sera plus jamais un fardeau.', 10, true),

('ia_pro', 'beginner', 'Créer une to-do list', 'Laissez l''IA organiser votre journée à votre place.', 'action', '{"task": "Dites à KITT IA : \"J''ai ces tâches à faire aujourd''hui : [listez 5 tâches]. Priorise-les par urgence/impact et suggère un ordre logique avec des créneaux horaires.\"", "hint": "Plus vous donnez de contexte, meilleure sera la prioritisation."}', 'Votre cerveau n''est pas fait pour mémoriser des listes. L''IA si.', 'To-do liste créée et priorisée. Vous allez être redoutablement efficace aujourd''hui.', 10, true),

('ia_pro', 'beginner', 'Comparer 2 outils', 'Utilisez l''IA pour faire un comparatif objectif en 2 minutes.', 'action', '{"task": "Demandez : \"Compare Notion et Obsidian pour un freelance qui veut organiser ses projets clients. Fais un tableau avec : prix, courbe d''apprentissage, points forts, limites.\"", "hint": "Demandez un tableau pour une lecture rapide."}', 'Avant de choisir un outil, faites travailler l''IA pour vous.', 'Comparatif généré. Vous venez d''éviter 2 heures de recherche Google. C''est ça, l''IA Pro.', 10, true),

-- ═══════════════ IA_PRO — INTERMEDIATE ═══════════════
('ia_pro', 'intermediate', 'Prompt chainé', 'Maîtrisez l''art du prompting en plusieurs étapes pour des résultats précis.', 'action', '{"task": "Enchaînez 3 prompts sur le même sujet : 1) \"Donne-moi une idée d''article sur le télétravail\" 2) \"Maintenant, développe un plan en 5 parties\" 3) \"Écris l''introduction en 150 mots, ton journalistique\". Observez comment chaque prompt affine le résultat.", "hint": "Chaque prompt est une itération — ne cherchez pas la perfection du premier coup."}', 'Un seul prompt c''est bien. Une chaîne de prompts, c''est de la magie.', 'Vous maîtrisez maintenant le prompting itératif — la compétence que 95% des utilisateurs IA ignorent.', 25, true),

('ia_pro', 'intermediate', 'Analyse SWOT avec l''IA', 'Générez une analyse stratégique complète en moins de 5 minutes.', 'action', '{"task": "Décrivez votre projet ou entreprise en 3 lignes, puis demandez : \"Fais une analyse SWOT complète. Pour chaque quadrant, donne 3 points concrets avec des actions recommandées.\"", "hint": "Plus votre description est précise, plus l''analyse sera pertinente."}', 'Vos concurrents passent des heures sur leur SWOT. Vous, 5 minutes.', 'Analyse SWOT générée. Vous avez maintenant une vision stratégique claire — utilisez-la.', 25, true),

('ia_pro', 'intermediate', 'Créer un persona client', 'Définissez votre client idéal grâce à l''IA.', 'action', '{"task": "Décrivez votre produit/service et demandez : \"Crée un persona client détaillé : prénom, âge, profession, frustrations, objectifs, comportement d''achat, canaux préférés. Rends-le réaliste et actionnable.\"", "hint": "Un bon persona inclut des citations directes imaginées de ce client."}', 'Vous pensez connaître votre client ? L''IA va vous surprendre.', 'Persona créé. Vous avez maintenant un visage sur votre client idéal — tout votre marketing change.', 25, true),

('ia_pro', 'intermediate', 'Automatiser un workflow', 'Identifiez et automatisez une tâche répétitive dans votre quotidien.', 'action', '{"task": "Décrivez une tâche que vous répétez chaque semaine (ex: rapport hebdo, relance clients) et demandez : \"Comment pourrais-je automatiser cette tâche avec des outils IA ? Donne-moi un workflow étape par étape avec les outils recommandés.\"", "hint": "Commencez par la tâche qui vous prend le plus de temps."}', 'Si vous le faites plus de 3 fois, c''est le travail de l''IA, pas le vôtre.', 'Workflow automatisé. Vous venez de vous libérer des heures chaque semaine. C''est du temps de vie récupéré.', 25, true),

('ia_pro', 'intermediate', 'Débugger un prompt', 'Apprenez à diagnostiquer et améliorer un prompt qui ne donne pas satisfaction.', 'action', '{"task": "Prenez un prompt qui vous a donné un résultat décevant. Demandez à KITT IA : \"Voici mon prompt : [prompt]. La réponse obtenue était décevante car [raison]. Analyse ce qui ne va pas et propose 3 versions améliorées avec explication.\"", "hint": "Un bon debuggage commence par identifier exactement ce qui manque : contexte, format, contraintes ?"}', 'Un mauvais prompt n''est pas un échec — c''est une opportunité d''apprendre.', 'Prompt débugué et amélioré. Vous venez d''acquérir le réflexe du prompting professionnel.', 25, true),

-- ═══════════════ IA_PRO — ADVANCED ═══════════════
('ia_pro', 'advanced', 'System prompt custom', 'Créez un system prompt sur mesure pour transformer KITT en expert dédié.', 'action', '{"task": "Rédigez un system prompt pour créer un assistant spécialisé dans votre domaine. Incluez : rôle, expertise, ton, contraintes, format de réponse. Testez-le avec 3 questions différentes.", "hint": "Le system prompt est la personnalité de votre IA — investissez du temps ici, ça impacte chaque échange."}', 'Un assistant IA généraliste, c''est bien. Un assistant IA calibré pour vous, c''est votre avantage compétitif.', 'System prompt maîtrisé. Vous construisez maintenant votre propre stack IA — c''est du niveau expert.', 50, true),

('ia_pro', 'advanced', 'Fine-tuning de réponse', 'Maîtrisez les techniques avancées pour contrôler précisément les outputs IA.', 'action', '{"task": "Prenez une réponse IA satisfaisante et appliquez 5 techniques de raffinement : 1) Contrainte de format strict 2) Injection d''exemples (few-shot) 3) Chain of thought 4) Instruction de persona expert 5) Calibration du ton. Comparez les résultats.", "hint": "Documentez chaque technique et son impact — vous construisez votre playbook personnel."}', 'Entre un utilisateur IA basique et un expert, c''est le contrôle des outputs qui fait la différence.', 'Techniques de fine-tuning maîtrisées. Votre playbook de prompting expert est en construction.', 50, true),

('ia_pro', 'advanced', 'Créer un agent IA', 'Concevez l''architecture d''un agent IA autonome pour votre cas d''usage.', 'action', '{"task": "Définissez un problème complexe (ex: veille concurrentielle automatique) et demandez à KITT IA de vous aider à concevoir : 1) Les étapes de raisonnement de l''agent 2) Les outils nécessaires 3) Les critères de succès 4) Les garde-fous à mettre en place.", "hint": "Un bon agent a un objectif précis, des outils définis et des conditions d''arrêt claires."}', 'Les agents IA, c''est l''avenir du travail. Aujourd''hui, vous apprenez à les concevoir.', 'Architecture d''agent conçue. Vous pensez maintenant en systèmes — c''est la compétence la plus rare du marché.', 50, true),

('ia_pro', 'advanced', 'Benchmark de modèles', 'Évaluez objectivement différents LLMs sur votre cas d''usage spécifique.', 'action', '{"task": "Choisissez 3 tâches représentatives de votre usage quotidien. Testez chacune sur au moins 2 modèles différents (GPT-4, Claude, Gemini). Créez une matrice de comparaison : qualité, vitesse, coût, fiabilité. Concluez avec une recommandation argumentée.", "hint": "Le meilleur modèle n''existe pas — il y a le meilleur modèle pour votre cas d''usage."}', 'Tous les modèles IA ne se valent pas. Il''est temps de choisir vos armes avec méthode.', 'Benchmark réalisé. Vous avez maintenant une opinion éclairée sur les LLMs — pas une opinion de influenceur tech.', 50, true),

('ia_pro', 'advanced', 'Audit de prompt', 'Auditez et optimisez votre bibliothèque de prompts pour maximiser leur efficacité.', 'action', '{"task": "Listez vos 5 prompts les plus utilisés. Pour chacun, analysez : clarté de l''objectif, qualité du contexte, format demandé, gestion des edge cases. Réécrivez chacun en version optimisée v2.0.", "hint": "Un prompt audité régulièrement est un actif qui prend de la valeur — traitez-le comme tel."}', 'Vos prompts sont vos outils de travail. Un outil mal affûté vous ralentit sans que vous le sachiez.', 'Audit terminé. Vos prompts v2.0 vont transformer vos sessions de travail quotidiennes.', 50, true),

-- ═══════════════ IA_PERSO — BEGINNER ═══════════════
('ia_perso', 'beginner', 'Planifier un voyage', 'Laissez l''IA créer votre itinéraire de voyage personnalisé.', 'action', '{"task": "Dites à KITT IA : \"Planifie un week-end à [ville de votre choix] pour [nombre] personnes. Budget : [montant]. On aime [activités]. Évite les endroits trop touristiques. Format : jour par jour avec horaires approximatifs.\"", "hint": "Plus vous donnez vos préférences, plus l''itinéraire sera pertinent."}', 'Votre prochain voyage mérite mieux que TripAdvisor. L''IA va le personnaliser pour vous.', 'Itinéraire créé sur mesure ! Plus de vacances génériques — chaque voyage est maintenant une expérience unique.', 10, true),

('ia_perso', 'beginner', 'Recette personnalisée', 'Générez une recette adaptée à ce que vous avez dans votre frigo.', 'action', '{"task": "Listez les 5-8 ingrédients principaux de votre frigo et demandez : \"Crée une recette savoureuse avec ces ingrédients. Niveau : facile. Temps max : 30 min. Ajoute les étapes et les quantités exactes.\"", "hint": "Précisez vos contraintes alimentaires si nécessaire."}', 'Plus d''excuses pour commander à livraison. Votre frigo cache un chef étoilé.', 'Recette générée ! Vous venez de transformer des restes en repas. C''est ça l''IA au quotidien.', 10, true),

('ia_perso', 'beginner', 'Rédiger un CV moderne', 'Modernisez ou créez votre CV avec l''aide de l''IA.', 'action', '{"task": "Partagez votre expérience (poste, durée, responsabilités) et demandez : \"Reformule ces expériences avec des verbes d''action forts et des résultats quantifiés. Style : moderne et percutant. Adapté pour [secteur cible].\"", "hint": "Les recruteurs lisent un CV en 6 secondes — chaque mot compte."}', 'Votre CV actuel raconte vos tâches. L''IA va le transformer pour raconter vos victoires.', 'CV transformé ! Vous avez maintenant un CV qui se démarque — le premier filtre ATS ne vous arrêtera plus.', 10, true),

('ia_perso', 'beginner', 'Traduire un texte', 'Utilisez l''IA pour des traductions contextuelles de qualité professionnelle.', 'action', '{"task": "Prenez un texte de 100-200 mots (email pro, article, contrat simple) et demandez : \"Traduis ce texte en [langue] en conservant le ton et le niveau de formalité. Explique les 3 choix de traduction les plus importants.\"", "hint": "Demandez les explications — vous progresserez en langue en même temps."}', 'Google Translate traduit des mots. L''IA traduit du sens. La différence est immense.', 'Traduction pro réalisée. Vous venez de voir pourquoi l''IA dépasse tous les outils de traduction traditionnels.', 10, true),

('ia_perso', 'beginner', 'Organiser sa semaine', 'Créez un planning optimal avec l''IA comme coach de productivité personnel.', 'action', '{"task": "Listez vos obligations de la semaine (travail, famille, perso) et vos 3 priorités. Demandez : \"Crée un planning hebdomadaire réaliste avec des créneaux de travail concentré, des pauses et du temps pour les imprévus. Intègre la règle des 3 tâches prioritaires.\"", "hint": "Un bon planning inclut des buffers — la vie déborde toujours."}', 'Une semaine sans plan, c''est naviguer sans boussole. Votre semaine mérite mieux.', 'Planning de la semaine créé ! Vous allez être focus, efficace et serein. La semaine parfaite commence maintenant.', 10, true),

-- ═══════════════ IA_PERSO — INTERMEDIATE ═══════════════
('ia_perso', 'intermediate', 'Budget mensuel intelligent', 'Créez un système de budget personnalisé et réaliste avec l''IA.', 'action', '{"task": "Partagez vos revenus et grandes catégories de dépenses. Demandez : \"Crée un budget mensuel équilibré avec la règle 50/30/20 adaptée à ma situation. Suggère 3 optimisations concrètes pour économiser sans sacrifier ma qualité de vie.\"", "hint": "Soyez honnête sur vos dépenses réelles — l''IA ne juge pas."}', 'L''argent ne se gère pas au feeling. 5 minutes avec l''IA et vous avez un système.', 'Budget créé ! Vous venez de poser les bases de votre liberté financière. Chaque euro compte maintenant.', 25, true),

('ia_perso', 'intermediate', 'Lettre de motivation percutante', 'Rédigez une lettre de motivation qui sort vraiment du lot.', 'action', '{"task": "Donnez l''offre d''emploi et vos 3 expériences les plus pertinentes. Demandez : \"Rédige une lettre de motivation de 250 mots maximum. Structure : accroche mémorable, valeur ajoutée unique, projection dans le poste. Évite les clichés habituels.\"", "hint": "La meilleure lettre raconte une histoire, pas une liste de compétences."}', 'Votre lettre de motivation actuelle ressemble à celle de mille autres candidats. Changeons ça maintenant.', 'Lettre rédigée ! Vous venez de passer dans le top 5% des candidatures. Le recruteur va s''en souvenir.', 25, true),

('ia_perso', 'intermediate', 'Aide aux devoirs IA', 'Maîtrisez l''art d''utiliser l''IA comme tuteur pour vous (ou vos enfants).', 'action', '{"task": "Choisissez un concept difficile que vous ou un enfant de votre entourage avez du mal à comprendre. Demandez : \"Explique [concept] avec 3 niveaux de complexité : enfant de 8 ans, lycéen, adulte. Ajoute un exemple concret pour chaque niveau.\"", "hint": "L''IA est le tuteur infiniment patient qui n''existe pas dans la vraie vie."}', 'Comprendre n''a pas de prix. Et maintenant, vous avez un tuteur disponible 24h/24.', 'Concept maîtrisé ! L''apprentissage adaptatif avec l''IA — vous venez de découvrir le futur de l''éducation.', 25, true),

('ia_perso', 'intermediate', 'Comparer des assurances', 'Utilisez l''IA pour démystifier et comparer vos contrats d''assurance.', 'action', '{"task": "Prenez les points clés de vos contrats actuels et demandez : \"Explique en langage simple ces clauses d''assurance et identifie les doublons ou les manques. Quelles questions dois-je poser à mon assureur ?\"", "hint": "Copiez directement les clauses les plus obscures — c''est là que l''IA brille vraiment."}', 'Les assureurs écrivent pour être incompréhensibles. L''IA traduit pour vous.', 'Analyse terminée ! Vous comprenez maintenant vos contrats — et vous savez exactement quoi renégocier.', 25, true),

('ia_perso', 'intermediate', 'Préparer un entretien', 'Simulez et préparez votre entretien professionnel avec l''IA comme jury.', 'action', '{"task": "Partagez le poste visé et demandez : \"Joue le rôle d''un recruteur exigeant. Pose-moi les 5 questions difficiles les plus probables pour ce poste. Après chaque réponse que je donne, analyse-la et suggère comment l''améliorer.\"", "hint": "Ne trichez pas — répondez comme si c''était le vrai entretien."}', 'Les entretiens se préparent. Ceux qui improvisent échouent — vous ne ferez pas partie d''eux.', 'Entretien simulé ! Vous êtes maintenant préparé à 90% des questions. Le poste est à vous.', 25, true),

-- ═══════════════ IA_PERSO — ADVANCED ═══════════════
('ia_perso', 'advanced', 'Business plan simplifié', 'Créez les bases d''un business plan solide avec l''IA comme partenaire stratégique.', 'action', '{"task": "Décrivez votre idée business en 5 lignes. Demandez : \"Crée un business plan d''une page avec : problème résolu, cible, proposition de valeur unique, modèle de revenus, 3 risques principaux et comment les mitiger.\"", "hint": "Un bon business plan tient sur une page — sinon c''est de la procrastination déguisée."}', 'Une idée sans plan, c''est un rêve. Avec l''IA, transformons votre rêve en projet viable maintenant.', 'Business plan créé ! Vous avez maintenant une vision claire de votre projet. L''aventure entrepreneuriale commence.', 50, true),

('ia_perso', 'advanced', 'Négocier son salaire', 'Préparez une négociation salariale béton avec données et stratégie.', 'action', '{"task": "Partagez votre poste, expérience et fourchette visée. Demandez : \"Prépare ma négociation salariale : arguments basés sur la valeur marché, techniques de réponse aux objections classiques, script pour annoncer ma fourchette, et phrase d''ouverture percutante.\"", "hint": "Celui qui annonce le premier chiffre perd — préparez votre contre-stratégie."}', 'Chaque année sans négocier vous coûte en moyenne 5 000€. Aujourd''hui, vous apprenez à négocier.', 'Stratégie de négociation maîtrisée. Vous avez maintenant les arguments et les techniques. Maintenant, négociez.', 50, true),

('ia_perso', 'advanced', 'Script de podcast', 'Créez un script de podcast professionnel sur votre domaine d''expertise.', 'action', '{"task": "Choisissez un sujet dans votre domaine. Demandez : \"Crée le script complet d''un épisode de podcast de 15 minutes sur ce sujet. Inclus : accroche (30s), développement en 3 parties, moments d''interaction imaginés, conclusion mémorable et call-to-action.\"", "hint": "Un bon podcast raconte une histoire avec un arc narratif — évitez le style conférence."}', 'Votre expertise mérite d''être entendue. L''IA va vous aider à la scénariser.', 'Script créé ! Votre podcast peut commencer aujourd''hui. Vous avez la matière — il ne manque plus que le micro.', 50, true),

('ia_perso', 'advanced', 'Stratégie d''investissement', 'Construisez votre stratégie d''investissement personnelle avec l''IA comme conseiller.', 'action', '{"task": "Partagez votre profil (âge, horizon de placement, tolérance au risque, objectifs) et demandez : \"Crée une stratégie d''investissement personnalisée avec répartition d''actifs, véhicules recommandés (ETF, immobilier, etc.), et plan d''investissement mensuel réaliste.\" Note : ce n''est pas un conseil financier réglementé.", "hint": "Commencez par définir clairement votre objectif : retraite, liberté financière, achat immobilier ?"}', 'Votre argent travaille ou vous travaillez pour lui. Construisons votre stratégie financière maintenant.', 'Stratégie d''investissement construite ! Vous avez maintenant une roadmap financière. La prochaine étape : l''exécuter.', 50, true),

('ia_perso', 'advanced', 'Analyse juridique simple', 'Décryptez un contrat ou document juridique avec l''IA.', 'action', '{"task": "Prenez un contrat (bail, freelance, CGV) et demandez : \"Analyse ce contrat. Identifie : 1) Les 3 clauses les plus risquées pour moi 2) Ce qui manque et devrait y figurer 3) Les points à renégocier en priorité 4) Questions à poser à un avocat.\" Note : ceci ne remplace pas un conseil juridique professionnel.", "hint": "Concentrez-vous sur les clauses de résiliation, de responsabilité et de paiement."}', 'Les juristes facturent 300€/heure pour lire ce que l''IA peut analyser en 30 secondes.', 'Analyse juridique réalisée ! Vous comprenez maintenant votre contrat. Pour les enjeux importants, consultez toujours un avocat.', 50, true),

-- ═══════════════ CYBER — BEGINNER ═══════════════
('cyber', 'beginner', 'Vérifier un email phishing', 'Apprenez à identifier les signaux d''alerte d''un email frauduleux.', 'action', '{"task": "Demandez à KITT IA : \"Enseigne-moi les 7 signaux d''alerte d''un email de phishing avec un exemple concret pour chacun. Ensuite, crée un faux email de phishing pour que je m''entraîne à les repérer.\"", "hint": "90% des cyberattaques commencent par un email. Ce skill peut vous sauver."}', 'Un email peut vider votre compte bancaire en 10 minutes. Apprenons à les reconnaître.', 'Anti-phishing activé ! Vous faites maintenant partie des 10% qui ne se font pas avoir. Partagez ce skill.', 10, true),

('cyber', 'beginner', 'Créer un mot de passe fort', 'Maîtrisez la création et la gestion de mots de passe vraiment sécurisés.', 'action', '{"task": "Demandez : \"Explique pourquoi mon mot de passe habituel est probablement faible. Crée 3 méthodes pour générer des mots de passe forts et mémorables. Recommande-moi un gestionnaire de mots de passe avec comparatif.\"", "hint": "Un gestionnaire de mots de passe change tout — vous n''avez plus besoin de mémoriser."}', '123456 est encore le mot de passe le plus utilisé en France. Ne faites pas partie des statistiques.', 'Vos comptes sont maintenant mieux protégés. Un bon mot de passe = une porte blindée. Changez-les dès aujourd''hui.', 10, true),

('cyber', 'beginner', 'Activer le 2FA partout', 'Configurez l''authentification à deux facteurs sur vos comptes essentiels.', 'action', '{"task": "Demandez : \"Liste mes 10 comptes prioritaires où activer le 2FA (banque, email, réseaux sociaux, etc.) et explique pas à pas comment activer le 2FA sur Gmail et sur un réseau social. Quelle app 2FA recommandes-tu ?\"", "hint": "Le 2FA bloque 99,9% des attaques automatisées. C''est 2 minutes qui valent de l''or."}', '2 minutes pour activer le 2FA peuvent vous éviter 2 ans de galères. Faisons-le maintenant.', '2FA activé ! Vous venez d''ajouter un bouclier invisible sur vos comptes. Les hackers passent à la cible suivante.', 10, true),

('cyber', 'beginner', 'Scanner un site suspect', 'Apprenez à vérifier la légitimité d''un site web avant de saisir vos données.', 'action', '{"task": "Demandez à KITT IA : \"Donne-moi un protocole en 5 étapes pour vérifier si un site est sûr avant d''y entrer mes informations. Inclus les outils gratuits à utiliser et les signaux visuels à vérifier.\"", "hint": "HTTPS ne suffit pas — les sites phishing utilisent aussi le cadenas vert."}', 'Un faux site peut être identique à l''original. Savoir les distinguer, c''est une armure numérique.', 'Protocole de vérification maîtrisé ! Vous ne vous ferez plus piéger par une URL similaire ou un faux formulaire.', 10, true),

-- ═══════════════ CYBER — INTERMEDIATE ═══════════════
('cyber', 'intermediate', 'Audit de son empreinte numérique', 'Découvrez et maîtrisez ce que votre présence en ligne révèle sur vous.', 'action', '{"task": "Demandez : \"Guide-moi pour faire un audit de mon empreinte numérique : 1) Quoi googler sur moi-même 2) Comment vérifier les fuites de données (Have I Been Pwned) 3) Quelles informations supprimer en priorité 4) Comment me désinscrire des data brokers.\"", "hint": "Ce que vous trouvez en 5 minutes, un hacker le trouve aussi. Agissez avant lui."}', 'Savez-vous ce qu''un inconnu peut trouver sur vous en 10 minutes ? L''heure de le découvrir est venue.', 'Audit terminé. Vous connaissez maintenant votre surface d''attaque — et vous savez comment la réduire.', 25, true),

('cyber', 'intermediate', 'Configurer un VPN', 'Comprenez et configurez un VPN pour protéger votre vie privée en ligne.', 'action', '{"task": "Demandez : \"Explique exactement ce que fait un VPN (et ce qu''il ne fait PAS). Compare les 3 meilleurs VPN payants pour un usage personnel. Donne-moi un guide de configuration pas à pas pour le VPN recommandé.\"", "hint": "Un VPN n''est pas magique — comprendre ses limites est aussi important que l''utiliser."}', 'Sur un WiFi public, vos données circulent en clair. Un VPN change ça en 2 minutes.', 'VPN configuré et compris ! Vous naviguez maintenant de manière chiffrée. Votre FAI ne peut plus vous espionner.', 25, true),

('cyber', 'intermediate', 'Analyser les permissions d''une app', 'Auditez les applications de votre smartphone pour limiter votre exposition.', 'action', '{"task": "Demandez : \"Crée-moi un guide pour auditer les permissions de mes applications mobiles. Quelles permissions sont légitimes vs abusives pour chaque type d''app ? Donne-moi une liste de contrôle pour les 20 apps les plus courantes.\"", "hint": "Une lampe torche qui demande accès à vos contacts, c''est un signal d''alarme."}', 'Vos apps vous surveillent probablement en ce moment. Reprenons le contrôle maintenant.', 'Audit des permissions réalisé ! Vous avez désactivé des accès inutiles. Vos données personnelles vous appartiennent.', 25, true),

-- ═══════════════ CYBER — ADVANCED ═══════════════
('cyber', 'advanced', 'OSINT basique', 'Apprenez les techniques de renseignement en sources ouvertes pour vous protéger.', 'action', '{"task": "Demandez à KITT IA : \"Enseigne-moi les 5 techniques OSINT basiques utilisées par les hackers et recruteurs pour trouver des informations. Pour chacune, explique comment m''en protéger. Je veux comprendre pour mieux me défendre.\"", "hint": "L''OSINT est légal et éthique quand il sert à comprendre et à se protéger."}', 'Pour se défendre d''une attaque, il faut penser comme l''attaquant. C''est ce que vous allez apprendre maintenant.', 'OSINT maîtrisé ! Vous pensez maintenant comme un défenseur qui connaît les méthodes offensives. C''est le niveau expert.', 50, true),

('cyber', 'advanced', 'Simuler un phishing éducatif', 'Créez un exemple de phishing pour sensibiliser votre entourage.', 'action', '{"task": "Dans un but pédagogique, demandez : \"Aide-moi à créer un email de phishing d''entraînement (clairement marqué SIMULATION) pour sensibiliser mes collègues ou proches. Inclus : tous les signaux d''alerte visibles, le script de révélation après le test, et les points de formation clés.\"", "hint": "L''objectif est 100% pédagogique — révélez toujours immédiatement que c''est une simulation."}', 'La meilleure formation cybersécurité, c''est l''expérience vécue. Créons une simulation sûre et éducative.', 'Simulation créée ! Vous êtes maintenant un ambassadeur cybersécurité. Votre entourage est moins vulnérable grâce à vous.', 50, true),

('cyber', 'advanced', 'Red team thinking', 'Adoptez le mindset offensif pour identifier les failles de votre sécurité perso.', 'action', '{"task": "Demandez : \"En jouant le rôle d''un attaquant voulant compromettre mon compte email principal, liste les 10 méthodes d''attaque par ordre de probabilité. Pour chacune, donne la contre-mesure défensive à mettre en place.\"", "hint": "Documentez chaque contre-mesure et fixez-vous 30 jours pour toutes les implémenter."}', 'Les meilleures équipes de sécurité pensent comme les attaquants. Adoptez ce mindset maintenant.', 'Red team thinking activé ! Vous venez d''identifier et corriger vos 10 failles principales. Vous êtes une cible nettement plus difficile.', 50, true),

-- ═══════════════ VIBE_CODING — BEGINNER ═══════════════
('vibe_coding', 'beginner', 'Premier prompt Lovable', 'Créez votre première application web en langage naturel.', 'action', '{"task": "Dans Lovable, tapez : \"Crée une landing page pour [votre idée]. Elle doit avoir un titre accrocheur, une liste de 3 bénéfices et un bouton d''inscription.\" Observez le résultat et ajustez avec un deuxième prompt.", "hint": "Soyez précis sur le style : \"moderne et épuré\" ou \"coloré et dynamique\" change tout."}', 'Vous allez créer votre première app sans écrire une ligne de code. Prêt ?', 'Première app créée ! Vous venez de passer du côté des créateurs. Bienvenue dans le monde du Vibe Coding.', 10, true),

('vibe_coding', 'beginner', 'Modifier une couleur', 'Apprenez à personnaliser l''apparence de votre app avec des prompts précis.', 'action', '{"task": "Sur une app existante dans Lovable, demandez : \"Change la couleur principale en [couleur hex ou description]. Assure-toi que le texte reste lisible et que le design reste cohérent.\" Testez 3 palettes différentes.", "hint": "Utilisez les couleurs de votre marque ou choisissez sur coolors.co."}', 'Le design parle avant même que l''utilisateur lise un mot. Faites-le parler pour vous.', 'Couleurs modifiées ! Vous contrôlez maintenant le design de votre app — sans CSS, sans code. C''est la magie du Vibe Coding.', 10, true),

('vibe_coding', 'beginner', 'Ajouter un bouton fonctionnel', 'Intégrez une interaction utilisateur dans votre application.', 'action', '{"task": "Demandez à Lovable : \"Ajoute un bouton [nom] qui, au clic, affiche un message de confirmation stylisé. Le bouton doit être visible, avec un effet hover et une animation de clic.\"", "hint": "Décrivez l''interaction que vous voulez, pas le code — l''IA s''occupe du reste."}', 'Une app sans interaction, c''est une affiche. Ajoutons de la vie à votre projet.', 'Bouton ajouté et fonctionnel ! Vous comprenez maintenant comment les interactions se construisent avec des mots.', 10, true),

('vibe_coding', 'beginner', 'Déployer sur Lovable', 'Publiez votre application et obtenez une URL partageable.', 'action', '{"task": "Demandez à KITT IA : \"Comment déployer mon projet Lovable et le partager avec une URL publique ? Quelles vérifications faire avant de déployer ?\" Ensuite, déployez votre projet et partagez l''URL avec quelqu''un.", "hint": "Testez sur mobile avant de déployer — la majorité des utilisateurs viennent du mobile."}', 'Votre app mérite d''exister sur internet. Déployons-la maintenant.', 'Déployé ! Votre app est en ligne. Envoyez le lien à quelqu''un et regardez la magie opérer.', 10, true),

-- ═══════════════ VIBE_CODING — INTERMEDIATE ═══════════════
('vibe_coding', 'intermediate', 'Créer un formulaire complet', 'Construisez un formulaire fonctionnel avec validation et feedback utilisateur.', 'action', '{"task": "Demandez à Lovable : \"Crée un formulaire de contact avec : nom, email, message. Ajoute une validation en temps réel, un message d''erreur stylisé si l''email est invalide, et un message de succès après envoi. Design : épuré et professionnel.\"", "hint": "Testez tous les cas : champs vides, email invalide, envoi réussi — un bon formulaire gère tous les cas."}', 'Un formulaire bien fait, c''est la différence entre un lead converti et un utilisateur frustré.', 'Formulaire créé et validé ! Vous venez de construire quelque chose que des développeurs facturent des heures. En quelques prompts.', 25, true),

('vibe_coding', 'intermediate', 'Intégrer Supabase', 'Connectez une base de données à votre application pour persister les données.', 'action', '{"task": "Demandez : \"Connecte mon app Lovable à Supabase pour sauvegarder les soumissions du formulaire de contact dans une table. Crée la table nécessaire, ajoute les RLS policies de base et teste que les données s''enregistrent bien.\"", "hint": "Commencez simple : une table, quelques colonnes. La complexité vient ensuite."}', 'Une app sans base de données oublie tout. Lovable + Supabase = votre stack production.', 'Supabase intégré ! Vos données persistent maintenant. Vous venez de construire une vraie application full-stack.', 25, true),

('vibe_coding', 'intermediate', 'Créer une API simple', 'Construisez votre première Edge Function pour une logique backend.', 'action', '{"task": "Demandez : \"Crée une Edge Function Supabase qui reçoit un email en POST, vérifie qu''il est valide, et retourne un JSON avec {valid: true/false, message: string}. Montre-moi comment la tester.\"", "hint": "Une Edge Function = une fonction serverless. Pas besoin de serveur — c''est Supabase qui gère tout."}', 'Vous voulez de la logique backend sans gérer un serveur ? Les Edge Functions sont votre réponse.', 'API créée et testée ! Vous venez d''écrire votre première logique backend. C''est le niveau full-stack developer.', 25, true),

-- ═══════════════ VIBE_CODING — ADVANCED ═══════════════
('vibe_coding', 'advanced', 'Audit de code IA', 'Analysez et améliorez la qualité de votre code avec l''IA comme reviewer.', 'action', '{"task": "Prenez un composant React de votre projet et demandez : \"Fais un audit complet de ce code : 1) Problèmes de performance 2) Failles de sécurité potentielles 3) Mauvaises pratiques React 4) Accessibilité 5) Lisibilité. Propose la version améliorée pour chaque point.\"", "hint": "Un bon audit identifie les problèmes ET explique pourquoi c''est un problème."}', 'Écrire du code, c''est bien. Écrire du bon code, c''est mieux. Faisons un audit maintenant.', 'Audit terminé ! Votre code est plus propre, plus performant, plus sécurisé. C''est ce que font les seniors — vous aussi maintenant.', 50, true),

('vibe_coding', 'advanced', 'Optimiser les performances', 'Identifiez et résolvez les goulots d''étranglement de votre application.', 'action', '{"task": "Demandez : \"Mon app Lovable est lente sur mobile. Guide-moi pour : 1) Identifier les composants qui re-render trop souvent 2) Optimiser les images et assets 3) Réduire le bundle size 4) Ajouter du lazy loading 5) Mesurer l''amélioration avec des outils concrets.\"", "hint": "Un délai de 1 seconde réduit les conversions de 7%. La performance, c''est du business."}', 'Une app rapide, c''est une app utilisée. Optimisons votre projet pour qu''il vole.', 'Performances optimisées ! Votre app est plus rapide, plus légère. Vos utilisateurs vont remarquer la différence.', 50, true),

('vibe_coding', 'advanced', 'Débugger une Edge Function', 'Maîtrisez le debugging de fonctions serverless avec méthode.', 'action', '{"task": "Demandez : \"Ma Edge Function retourne une erreur 500. Voici le code : [collez votre code]. Voici les logs d''erreur : [collez les logs]. Analyse le problème étape par étape, identifie la cause racine et propose le fix avec explication.\"", "hint": "Les logs sont vos meilleurs amis — activez-les toujours en développement."}', 'Un bug non compris reviendra. Un bug debugué avec méthode disparaît pour toujours.', 'Bug résolu et compris ! Vous avez maintenant une méthode de debugging. C''est le skill qui sépare les amateurs des pros.', 50, true);